#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: make
# autospec version: v21
# autospec commit: 5424026
#
Name     : thin-provisioning-tools
Version  : 1.0.13
Release  : 12
URL      : https://github.com/jthornber/thin-provisioning-tools/archive/v1.0.13/thin-provisioning-tools-1.0.13.tar.gz
Source0  : https://github.com/jthornber/thin-provisioning-tools/archive/v1.0.13/thin-provisioning-tools-1.0.13.tar.gz
Source1  : http://localhost/cgit/vendor/thin-provisioning-tools/snapshot/thin-provisioning-tools-2024-07-30-16-03-19.tar.xz
Source2  : http://localhost/cgit/vendor/thin-provisioning-tools/snapshot/thin-provisioning-tools-2025-01-02-23-41-04.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : 0BSD Apache-2.0 BSD-3-Clause GPL-3.0 ICU MIT Unicode-DFS-2016 Unlicense Zlib
Requires: thin-provisioning-tools-bin = %{version}-%{release}
Requires: thin-provisioning-tools-license = %{version}-%{release}
Requires: thin-provisioning-tools-man = %{version}-%{release}
BuildRequires : autoconf
BuildRequires : automake
BuildRequires : automake-dev
BuildRequires : libtool-dev
BuildRequires : rustc
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
Introduction
============
A suite of tools for manipulating the metadata of the dm-thin, dm-cache and
dm-era device-mapper targets.

%package bin
Summary: bin components for the thin-provisioning-tools package.
Group: Binaries
Requires: thin-provisioning-tools-license = %{version}-%{release}

%description bin
bin components for the thin-provisioning-tools package.


%package license
Summary: license components for the thin-provisioning-tools package.
Group: Default

%description license
license components for the thin-provisioning-tools package.


%package man
Summary: man components for the thin-provisioning-tools package.
Group: Default

%description man
man components for the thin-provisioning-tools package.


%prep
%setup -q -n thin-provisioning-tools-1.0.13
cd %{_builddir}
tar xf %{_sourcedir}/thin-provisioning-tools-2024-07-30-16-03-19.tar.xz
cd %{_builddir}
tar xf %{_sourcedir}/thin-provisioning-tools-2025-01-02-23-41-04.tar.gz
cd %{_builddir}/thin-provisioning-tools-1.0.13
mkdir -p ./vendor
cp -r %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/* %{_builddir}/thin-provisioning-tools-1.0.13/./vendor
mkdir -p ./vendor
cp -r %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/* %{_builddir}/thin-provisioning-tools-1.0.13/./vendor
mkdir -p .cargo
echo '[source.crates-io]
replace-with = "vendored-sources"

[source."git+https://github.com/jthornber/rio?branch=master"]
git = "https://github.com/jthornber/rio"
branch = "master"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
' >> .cargo/config.toml

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1735861445
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
make  %{?_smp_mflags}


%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1735861445
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/thin-provisioning-tools
cp %{_builddir}/thin-provisioning-tools-%{version}/COPYING %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/8624bcdae55baeef00cd11d5dfcfa60f68710a02 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/adler/LICENSE-0BSD %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/3aedaafe8ea8fce424d1df3be32d1b8816944e0e || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/adler/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/1d47c63586fe3be7f228cff1ab0c029b53741875 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/adler/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/aho-corasick/COPYING %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/aho-corasick/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/4c8990add9180fc59efa5b0d8faf643c9709501e || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/aho-corasick/UNLICENSE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/anstyle/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/anstyle/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/f911b0506e6ba6a56b4edac717b461799f380ef0 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/anyhow/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/anyhow/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/atty/LICENSE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/3acad00f27f89710cd66d3f5528aed5046ac28d9 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/autocfg/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/autocfg/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/e6d32072ef5f584a805b429ecbd4eec428316dde || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/base64/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/base64/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/b716916e6b0b96af5ecadf1eaee25f966f5d6cb2 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/bitflags-1.3.2/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/bitflags-1.3.2/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/bitflags/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/bitflags/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/bytemuck/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/1c619b057a9bf7a8234b3105fcfb5b375e749db1 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/bytemuck/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/53e358de8d76c2bf7b8a7f899199592f2eb3fe77 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/bytemuck/LICENSE-ZLIB %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/59b5efd50c4508e7fa74828e7469187bbe5bd864 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/byteorder/COPYING %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/byteorder/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/4c8990add9180fc59efa5b0d8faf643c9709501e || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/byteorder/UNLICENSE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/cassowary/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/8205a96107bd2d30b9a078adcc9eea1bf5eccaf7 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/cassowary/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/86839b96a62723c6b7892a01b25908ff0c108447 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/cfg-if/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/cfg-if/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/clap/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/clap/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/4dbe8833d0189c691b308c3dd40fab84ef2e9630 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/clap_builder/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/clap_builder/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/8fe88f09d35c6054e0a780a793833c16fb888168 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/clap_lex/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/clap_lex/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/8fe88f09d35c6054e0a780a793833c16fb888168 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/console/LICENSE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/9a675655c0a9f0bb9c8109678651fe27bceaca04 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/crc32fast/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/crc32fast/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/8f178d4cc55689ebdd562cabb1282e33bf8f32fe || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/data-encoding/LICENSE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/7963d112b803d110d3e75e932c052284fd208629 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/downcast/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/d223c347f316d191419e643e479caa33bbeae672 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/duct/LICENSE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/4d1fd76d48096fec63c418c3c415a2ed5c2bb65d || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/encode_unicode/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/encode_unicode/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/188be4108decf997e0edd21c6dd83deaf320f255 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/env_logger/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/env_logger/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/errno/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/errno/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/7a842f34e127456338641b14c7a00ec246d89fb6 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/exitcode/LICENSE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/92170cdc034b2ff819323ff670d3b7266c8bffcd || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/fastrand/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/fastrand/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/fixedbitset/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/fixedbitset/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/0c160db99de1b5577d1160540f1a1312b01a3f5b || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/flate2/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/flate2/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/fragile/LICENSE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/getrandom/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/e9b475b5dccf14bd66d72dd12a04db75eaad1a9e || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/getrandom/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/c8eef3d34d69b1d62fd378fa02150a0bce62fd26 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/hermit-abi-0.1.19/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/hermit-abi-0.1.19/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/hermit-abi/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/hermit-abi/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/indicatif/LICENSE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/9a675655c0a9f0bb9c8109678651fe27bceaca04 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/instant/LICENSE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/037192733999bccd7ed8d75123b7ec09feb4a12d || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/iovec/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/4e652e854ac8bcfd9bb61be90d315464c51c4a7a || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/iovec/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/113187c68b7bc6023281590d4eb2a31c865768e1 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/lazy_static/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/lazy_static/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/2bf5cac862d5a0480b5d5bcd3a1852d68bfeee84 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/libc/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/libc/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/36d69bcb88153a640740000efe933b009420ce7e || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/linux-raw-sys/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/linux-raw-sys/LICENSE-Apache-2.0_WITH_LLVM-exception %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/f137043e018f2024e0414a9153ea728c203ae8e5 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/linux-raw-sys/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/log/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/log/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/memchr/COPYING %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/memchr/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/4c8990add9180fc59efa5b0d8faf643c9709501e || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/memchr/UNLICENSE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/minimal-lexical/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/5feaf15b3fa7d2d226d811e5fcd49098a1ea520c || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/minimal-lexical/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/minimal-lexical/LICENSE.md %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/cd3fe820606ed34ac2591caf068c7cabd3ab3509 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/miniz_oxide/LICENSE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/18d7fe3c54698817feec1f2e04a9d5a0f046a80c || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/miniz_oxide/LICENSE-APACHE.md %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/598f87f072f66e2269dd6919292b2934dbb20492 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/miniz_oxide/LICENSE-MIT.md %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/18d7fe3c54698817feec1f2e04a9d5a0f046a80c || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/miniz_oxide/LICENSE-ZLIB.md %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/11f0f1bee61ba6393c3dc7aefee7b92b604ff6c0 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/mockall/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/mockall/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/7410d07c3621242ce086802924f4c333ff5326bb || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/mockall_derive/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/mockall_derive/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/7410d07c3621242ce086802924f4c333ff5326bb || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/nom/LICENSE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/27ea6989d4f34b7b944eb884410a31ae20d11686 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/num-derive/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/num-derive/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/num-traits/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/num-traits/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/num_cpus/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/num_cpus/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/ec9737a4e769cce48d5c95d9c75a4ba5f29a2563 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/numtoa/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/a8f3e29d5eab4420318de979754f5637d4bf2c3f || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/numtoa/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/0eca98e4deae2a3e95f8a75d783067b5c66ff431 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/once_cell/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/once_cell/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/os_pipe/LICENSE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/4d1fd76d48096fec63c418c3c415a2ed5c2bb65d || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/portable-atomic/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/598f87f072f66e2269dd6919292b2934dbb20492 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/portable-atomic/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/ppv-lite86/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/088830dcb78eba1a2052df69bd5cba5445e8f2d7 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/ppv-lite86/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/e1c86f32641f01a5b85d6e9b20138e8470b883fc || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/predicates-core/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/a6a5418b4d67d9f3a33cbf184b25ac7f9fa87d33 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/predicates-core/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/26cc7e3e048b8c2b640f5b15273cb9c0a8737702 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/predicates-tree/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/a6a5418b4d67d9f3a33cbf184b25ac7f9fa87d33 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/predicates-tree/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/26cc7e3e048b8c2b640f5b15273cb9c0a8737702 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/predicates/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/92170cdc034b2ff819323ff670d3b7266c8bffcd || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/predicates/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/4dbe8833d0189c691b308c3dd40fab84ef2e9630 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/proc-macro2/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/proc-macro2/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/quick-xml/LICENSE-MIT.md %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/dc5a1036298990ac083baa9bf95f6a1b8ee98c0f || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/quickcheck/COPYING %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/quickcheck/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/4c8990add9180fc59efa5b0d8faf643c9709501e || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/quickcheck/UNLICENSE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/quickcheck_macros/COPYING %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/quickcheck_macros/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/4c8990add9180fc59efa5b0d8faf643c9709501e || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/quickcheck_macros/UNLICENSE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/quote/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/quote/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/rand/COPYRIGHT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/f14afa20edce530124d39cd56312c7781c19b267 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/rand/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/4632a631b427f005d97734ea8c6a44090fec5cd9 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/rand/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/d74ad13f1402c35008f22bc588a6b8199ed164d3 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/rand_chacha/COPYRIGHT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/f14afa20edce530124d39cd56312c7781c19b267 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/rand_chacha/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/e9b475b5dccf14bd66d72dd12a04db75eaad1a9e || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/rand_chacha/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/d74ad13f1402c35008f22bc588a6b8199ed164d3 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/rand_core/COPYRIGHT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/f14afa20edce530124d39cd56312c7781c19b267 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/rand_core/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/0ff30cb09f7056217d089f352fe089b49971eeae || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/rand_core/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/d74ad13f1402c35008f22bc588a6b8199ed164d3 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/rangemap/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/2a4d7916e54f20cbbb73ffeef2d39a505f1c8394 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/rangemap/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/84bd3ae90fc5fc9eba1babed8039e5085de0d82c || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/redox_syscall/LICENSE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/a00165152c82ea55b9fc254890dc8860c25e3bb6 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/redox_termios/LICENSE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/4d9d82e016d0ca83bb1f9fb73affcb6d4826a13f || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/regex-automata/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/regex-automata/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/regex-syntax/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/regex-syntax/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/regex-syntax/src/unicode_tables/LICENSE-UNICODE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/68d12a03b339648117165b9c021b93f26974d6f6 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/regex/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/regex/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/roaring/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/roaring/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/78b5f27c62ea1f4f238b54f988ea5ddaf65b2a52 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/rustc_version/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/rustc_version/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/9a2b6b4ad55ec42cf19fc686c74668d3a6303ae7 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/rustix/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/rustix/LICENSE-Apache-2.0_WITH_LLVM-exception %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/f137043e018f2024e0414a9153ea728c203ae8e5 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/rustix/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/safemem/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/aca374a3362a76702c50bd4e7d590a57f8834fc7 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/safemem/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/8838cf14748354bdd25b37507bbb8940248ea5c0 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/semver/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/semver/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/shared_child/LICENSE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/4d1fd76d48096fec63c418c3c415a2ed5c2bb65d || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/strsim/LICENSE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/f5feee4154156527645a9b18ef29da23fc859ca9 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/syn-1.0.109/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/syn-1.0.109/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/syn/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/syn/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/tempfile/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/tempfile/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/70693ba8757c4a17af68e39ab32e4e0d4a389416 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/termion/LICENSE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/23d2ff0bc13a8156fb333f0e218420873a838415 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/termtree/LICENSE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/19b4f6d5815ac866d69353dd925e66db58a24a77 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/thiserror-impl/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/thiserror-impl/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/thiserror/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/thiserror/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/threadpool/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/threadpool/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/tui/LICENSE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/1415f5af65c00e779681ee40238f3410f156a05b || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/unicode-ident/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/unicode-ident/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/unicode-ident/LICENSE-UNICODE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/583a5eebcf6119730bd96922e8a0faecf7faf720 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/unicode-segmentation/COPYRIGHT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/5ed53061419caf64f84d064f3641392a2a10fa7f || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/unicode-segmentation/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/unicode-segmentation/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/60c3522081bf15d7ac1d4c5a63de425ef253e87a || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/unicode-width/COPYRIGHT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/5ed53061419caf64f84d064f3641392a2a10fa7f || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/unicode-width/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/unicode-width/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/60c3522081bf15d7ac1d4c5a63de425ef253e87a || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/wasi/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/wasi/LICENSE-Apache-2.0_WITH_LLVM-exception %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/f137043e018f2024e0414a9153ea728c203ae8e5 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/wasi/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/winapi/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/92170cdc034b2ff819323ff670d3b7266c8bffcd || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/winapi/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/2243f7a86daaa727d34d92e987a741036f288464 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/windows-sys/license-apache-2.0 %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/windows-sys/license-mit %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/windows-targets/license-apache-2.0 %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/windows-targets/license-mit %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/windows_aarch64_gnullvm/license-apache-2.0 %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/windows_aarch64_gnullvm/license-mit %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/windows_aarch64_msvc/license-apache-2.0 %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/windows_aarch64_msvc/license-mit %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/windows_i686_gnu/license-apache-2.0 %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/windows_i686_gnu/license-mit %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/windows_i686_gnullvm/license-apache-2.0 %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/windows_i686_gnullvm/license-mit %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/windows_i686_msvc/license-apache-2.0 %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/windows_i686_msvc/license-mit %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/windows_x86_64_gnu/license-apache-2.0 %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/windows_x86_64_gnu/license-mit %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/windows_x86_64_gnullvm/license-apache-2.0 %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/windows_x86_64_gnullvm/license-mit %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/windows_x86_64_msvc/license-apache-2.0 %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/thin-provisioning-tools-2024-07-30-16-03-19/windows_x86_64_msvc/license-mit %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/adler/LICENSE-0BSD %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/3aedaafe8ea8fce424d1df3be32d1b8816944e0e || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/adler/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/1d47c63586fe3be7f228cff1ab0c029b53741875 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/adler/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/aho-corasick/COPYING %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/aho-corasick/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/4c8990add9180fc59efa5b0d8faf643c9709501e || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/aho-corasick/UNLICENSE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/anstyle/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/anstyle/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/f911b0506e6ba6a56b4edac717b461799f380ef0 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/anyhow/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/anyhow/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/atty/LICENSE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/3acad00f27f89710cd66d3f5528aed5046ac28d9 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/autocfg/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/autocfg/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/e6d32072ef5f584a805b429ecbd4eec428316dde || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/base64/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/base64/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/b716916e6b0b96af5ecadf1eaee25f966f5d6cb2 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/bitflags-1.3.2/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/bitflags-1.3.2/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/bitflags/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/bitflags/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/bytemuck/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/1c619b057a9bf7a8234b3105fcfb5b375e749db1 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/bytemuck/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/53e358de8d76c2bf7b8a7f899199592f2eb3fe77 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/bytemuck/LICENSE-ZLIB %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/59b5efd50c4508e7fa74828e7469187bbe5bd864 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/byteorder/COPYING %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/byteorder/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/4c8990add9180fc59efa5b0d8faf643c9709501e || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/byteorder/UNLICENSE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/cassowary/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/8205a96107bd2d30b9a078adcc9eea1bf5eccaf7 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/cassowary/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/86839b96a62723c6b7892a01b25908ff0c108447 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/cfg-if/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/cfg-if/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/clap/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/clap/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/4dbe8833d0189c691b308c3dd40fab84ef2e9630 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/clap_builder/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/clap_builder/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/8fe88f09d35c6054e0a780a793833c16fb888168 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/clap_lex/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/clap_lex/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/8fe88f09d35c6054e0a780a793833c16fb888168 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/console/LICENSE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/9a675655c0a9f0bb9c8109678651fe27bceaca04 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/crc32fast/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/crc32fast/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/8f178d4cc55689ebdd562cabb1282e33bf8f32fe || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/data-encoding/LICENSE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/7963d112b803d110d3e75e932c052284fd208629 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/downcast/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/d223c347f316d191419e643e479caa33bbeae672 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/duct/LICENSE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/4d1fd76d48096fec63c418c3c415a2ed5c2bb65d || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/encode_unicode/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/encode_unicode/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/188be4108decf997e0edd21c6dd83deaf320f255 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/env_logger/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/env_logger/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/errno/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/errno/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/7a842f34e127456338641b14c7a00ec246d89fb6 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/exitcode/LICENSE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/92170cdc034b2ff819323ff670d3b7266c8bffcd || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/fastrand/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/fastrand/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/fixedbitset/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/fixedbitset/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/0c160db99de1b5577d1160540f1a1312b01a3f5b || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/flate2/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/flate2/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/fragile/LICENSE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/getrandom/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/e9b475b5dccf14bd66d72dd12a04db75eaad1a9e || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/getrandom/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/c8eef3d34d69b1d62fd378fa02150a0bce62fd26 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/hermit-abi-0.1.19/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/hermit-abi-0.1.19/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/hermit-abi/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/hermit-abi/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/indicatif/LICENSE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/9a675655c0a9f0bb9c8109678651fe27bceaca04 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/instant/LICENSE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/037192733999bccd7ed8d75123b7ec09feb4a12d || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/iovec/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/4e652e854ac8bcfd9bb61be90d315464c51c4a7a || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/iovec/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/113187c68b7bc6023281590d4eb2a31c865768e1 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/lazy_static/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/lazy_static/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/2bf5cac862d5a0480b5d5bcd3a1852d68bfeee84 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/libc/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/libc/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/36d69bcb88153a640740000efe933b009420ce7e || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/linux-raw-sys/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/linux-raw-sys/LICENSE-Apache-2.0_WITH_LLVM-exception %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/f137043e018f2024e0414a9153ea728c203ae8e5 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/linux-raw-sys/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/log/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/log/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/memchr/COPYING %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/memchr/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/4c8990add9180fc59efa5b0d8faf643c9709501e || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/memchr/UNLICENSE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/minimal-lexical/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/5feaf15b3fa7d2d226d811e5fcd49098a1ea520c || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/minimal-lexical/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/minimal-lexical/LICENSE.md %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/cd3fe820606ed34ac2591caf068c7cabd3ab3509 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/miniz_oxide/LICENSE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/18d7fe3c54698817feec1f2e04a9d5a0f046a80c || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/miniz_oxide/LICENSE-APACHE.md %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/598f87f072f66e2269dd6919292b2934dbb20492 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/miniz_oxide/LICENSE-MIT.md %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/18d7fe3c54698817feec1f2e04a9d5a0f046a80c || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/miniz_oxide/LICENSE-ZLIB.md %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/11f0f1bee61ba6393c3dc7aefee7b92b604ff6c0 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/mockall/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/mockall/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/7410d07c3621242ce086802924f4c333ff5326bb || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/mockall_derive/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/mockall_derive/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/7410d07c3621242ce086802924f4c333ff5326bb || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/nom/LICENSE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/27ea6989d4f34b7b944eb884410a31ae20d11686 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/num-derive/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/num-derive/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/num-traits/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/num-traits/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/num_cpus/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/num_cpus/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/ec9737a4e769cce48d5c95d9c75a4ba5f29a2563 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/numtoa/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/a8f3e29d5eab4420318de979754f5637d4bf2c3f || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/numtoa/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/0eca98e4deae2a3e95f8a75d783067b5c66ff431 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/once_cell/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/once_cell/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/os_pipe/LICENSE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/4d1fd76d48096fec63c418c3c415a2ed5c2bb65d || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/portable-atomic/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/598f87f072f66e2269dd6919292b2934dbb20492 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/portable-atomic/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/ppv-lite86/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/088830dcb78eba1a2052df69bd5cba5445e8f2d7 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/ppv-lite86/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/e1c86f32641f01a5b85d6e9b20138e8470b883fc || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/predicates-core/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/a6a5418b4d67d9f3a33cbf184b25ac7f9fa87d33 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/predicates-core/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/26cc7e3e048b8c2b640f5b15273cb9c0a8737702 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/predicates-tree/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/a6a5418b4d67d9f3a33cbf184b25ac7f9fa87d33 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/predicates-tree/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/26cc7e3e048b8c2b640f5b15273cb9c0a8737702 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/predicates/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/92170cdc034b2ff819323ff670d3b7266c8bffcd || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/predicates/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/4dbe8833d0189c691b308c3dd40fab84ef2e9630 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/proc-macro2/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/proc-macro2/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/quick-xml/LICENSE-MIT.md %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/dc5a1036298990ac083baa9bf95f6a1b8ee98c0f || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/quickcheck/COPYING %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/quickcheck/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/4c8990add9180fc59efa5b0d8faf643c9709501e || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/quickcheck/UNLICENSE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/quickcheck_macros/COPYING %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/quickcheck_macros/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/4c8990add9180fc59efa5b0d8faf643c9709501e || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/quickcheck_macros/UNLICENSE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/quote/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/quote/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/rand/COPYRIGHT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/f14afa20edce530124d39cd56312c7781c19b267 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/rand/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/4632a631b427f005d97734ea8c6a44090fec5cd9 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/rand/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/d74ad13f1402c35008f22bc588a6b8199ed164d3 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/rand_chacha/COPYRIGHT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/f14afa20edce530124d39cd56312c7781c19b267 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/rand_chacha/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/e9b475b5dccf14bd66d72dd12a04db75eaad1a9e || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/rand_chacha/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/d74ad13f1402c35008f22bc588a6b8199ed164d3 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/rand_core/COPYRIGHT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/f14afa20edce530124d39cd56312c7781c19b267 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/rand_core/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/0ff30cb09f7056217d089f352fe089b49971eeae || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/rand_core/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/d74ad13f1402c35008f22bc588a6b8199ed164d3 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/rangemap/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/2a4d7916e54f20cbbb73ffeef2d39a505f1c8394 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/rangemap/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/84bd3ae90fc5fc9eba1babed8039e5085de0d82c || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/redox_syscall/LICENSE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/a00165152c82ea55b9fc254890dc8860c25e3bb6 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/redox_termios/LICENSE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/4d9d82e016d0ca83bb1f9fb73affcb6d4826a13f || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/regex-automata/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/regex-automata/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/regex-syntax/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/regex-syntax/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/regex-syntax/src/unicode_tables/LICENSE-UNICODE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/68d12a03b339648117165b9c021b93f26974d6f6 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/regex/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/regex/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/roaring/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/roaring/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/78b5f27c62ea1f4f238b54f988ea5ddaf65b2a52 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/rustc_version/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/rustc_version/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/9a2b6b4ad55ec42cf19fc686c74668d3a6303ae7 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/rustix/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/rustix/LICENSE-Apache-2.0_WITH_LLVM-exception %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/f137043e018f2024e0414a9153ea728c203ae8e5 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/rustix/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/safemem/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/aca374a3362a76702c50bd4e7d590a57f8834fc7 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/safemem/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/8838cf14748354bdd25b37507bbb8940248ea5c0 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/semver/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/semver/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/shared_child/LICENSE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/4d1fd76d48096fec63c418c3c415a2ed5c2bb65d || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/strsim/LICENSE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/f5feee4154156527645a9b18ef29da23fc859ca9 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/syn-1.0.109/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/syn-1.0.109/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/syn/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/syn/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/tempfile/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/tempfile/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/70693ba8757c4a17af68e39ab32e4e0d4a389416 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/termion/LICENSE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/23d2ff0bc13a8156fb333f0e218420873a838415 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/termtree/LICENSE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/19b4f6d5815ac866d69353dd925e66db58a24a77 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/thiserror-impl/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/thiserror-impl/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/thiserror/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/thiserror/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/threadpool/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/threadpool/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/tui/LICENSE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/1415f5af65c00e779681ee40238f3410f156a05b || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/unicode-ident/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/unicode-ident/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/unicode-ident/LICENSE-UNICODE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/583a5eebcf6119730bd96922e8a0faecf7faf720 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/unicode-segmentation/COPYRIGHT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/5ed53061419caf64f84d064f3641392a2a10fa7f || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/unicode-segmentation/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/unicode-segmentation/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/60c3522081bf15d7ac1d4c5a63de425ef253e87a || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/unicode-width/COPYRIGHT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/5ed53061419caf64f84d064f3641392a2a10fa7f || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/unicode-width/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/unicode-width/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/60c3522081bf15d7ac1d4c5a63de425ef253e87a || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/wasi/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/wasi/LICENSE-Apache-2.0_WITH_LLVM-exception %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/f137043e018f2024e0414a9153ea728c203ae8e5 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/wasi/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/winapi/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/92170cdc034b2ff819323ff670d3b7266c8bffcd || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/winapi/LICENSE-MIT %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/2243f7a86daaa727d34d92e987a741036f288464 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/windows-sys/license-apache-2.0 %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/windows-sys/license-mit %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/windows-targets/license-apache-2.0 %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/windows-targets/license-mit %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/windows_aarch64_gnullvm/license-apache-2.0 %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/windows_aarch64_gnullvm/license-mit %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/windows_aarch64_msvc/license-apache-2.0 %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/windows_aarch64_msvc/license-mit %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/windows_i686_gnu/license-apache-2.0 %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/windows_i686_gnu/license-mit %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/windows_i686_gnullvm/license-apache-2.0 %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/windows_i686_gnullvm/license-mit %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/windows_i686_msvc/license-apache-2.0 %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/windows_i686_msvc/license-mit %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/windows_x86_64_gnu/license-apache-2.0 %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/windows_x86_64_gnu/license-mit %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/windows_x86_64_gnullvm/license-apache-2.0 %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/windows_x86_64_gnullvm/license-mit %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/windows_x86_64_msvc/license-apache-2.0 %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/thin-provisioning-tools-2025-01-02-23-41-04/windows_x86_64_msvc/license-mit %{buildroot}/usr/share/package-licenses/thin-provisioning-tools/689ec0681815ecc32bee639c68e7740add7bd301 || :
export GOAMD64=v2
GOAMD64=v2
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/cache_check
/usr/bin/cache_dump
/usr/bin/cache_metadata_size
/usr/bin/cache_repair
/usr/bin/cache_restore
/usr/bin/cache_writeback
/usr/bin/era_check
/usr/bin/era_dump
/usr/bin/era_invalidate
/usr/bin/era_restore
/usr/bin/pdata_tools
/usr/bin/thin_check
/usr/bin/thin_delta
/usr/bin/thin_dump
/usr/bin/thin_ls
/usr/bin/thin_metadata_pack
/usr/bin/thin_metadata_size
/usr/bin/thin_metadata_unpack
/usr/bin/thin_repair
/usr/bin/thin_restore
/usr/bin/thin_rmap
/usr/bin/thin_trim

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/thin-provisioning-tools/037192733999bccd7ed8d75123b7ec09feb4a12d
/usr/share/package-licenses/thin-provisioning-tools/088830dcb78eba1a2052df69bd5cba5445e8f2d7
/usr/share/package-licenses/thin-provisioning-tools/0c160db99de1b5577d1160540f1a1312b01a3f5b
/usr/share/package-licenses/thin-provisioning-tools/0eca98e4deae2a3e95f8a75d783067b5c66ff431
/usr/share/package-licenses/thin-provisioning-tools/0ff30cb09f7056217d089f352fe089b49971eeae
/usr/share/package-licenses/thin-provisioning-tools/113187c68b7bc6023281590d4eb2a31c865768e1
/usr/share/package-licenses/thin-provisioning-tools/11f0f1bee61ba6393c3dc7aefee7b92b604ff6c0
/usr/share/package-licenses/thin-provisioning-tools/1415f5af65c00e779681ee40238f3410f156a05b
/usr/share/package-licenses/thin-provisioning-tools/188be4108decf997e0edd21c6dd83deaf320f255
/usr/share/package-licenses/thin-provisioning-tools/18d7fe3c54698817feec1f2e04a9d5a0f046a80c
/usr/share/package-licenses/thin-provisioning-tools/19b4f6d5815ac866d69353dd925e66db58a24a77
/usr/share/package-licenses/thin-provisioning-tools/1c619b057a9bf7a8234b3105fcfb5b375e749db1
/usr/share/package-licenses/thin-provisioning-tools/1d47c63586fe3be7f228cff1ab0c029b53741875
/usr/share/package-licenses/thin-provisioning-tools/2243f7a86daaa727d34d92e987a741036f288464
/usr/share/package-licenses/thin-provisioning-tools/23d2ff0bc13a8156fb333f0e218420873a838415
/usr/share/package-licenses/thin-provisioning-tools/26cc7e3e048b8c2b640f5b15273cb9c0a8737702
/usr/share/package-licenses/thin-provisioning-tools/27ea6989d4f34b7b944eb884410a31ae20d11686
/usr/share/package-licenses/thin-provisioning-tools/2a4d7916e54f20cbbb73ffeef2d39a505f1c8394
/usr/share/package-licenses/thin-provisioning-tools/2b8b815229aa8a61e483fb4ba0588b8b6c491890
/usr/share/package-licenses/thin-provisioning-tools/2bf5cac862d5a0480b5d5bcd3a1852d68bfeee84
/usr/share/package-licenses/thin-provisioning-tools/36d69bcb88153a640740000efe933b009420ce7e
/usr/share/package-licenses/thin-provisioning-tools/3acad00f27f89710cd66d3f5528aed5046ac28d9
/usr/share/package-licenses/thin-provisioning-tools/3aedaafe8ea8fce424d1df3be32d1b8816944e0e
/usr/share/package-licenses/thin-provisioning-tools/3b042d3d971924ec0296687efd50dbe08b734976
/usr/share/package-licenses/thin-provisioning-tools/4632a631b427f005d97734ea8c6a44090fec5cd9
/usr/share/package-licenses/thin-provisioning-tools/4c8990add9180fc59efa5b0d8faf643c9709501e
/usr/share/package-licenses/thin-provisioning-tools/4d1fd76d48096fec63c418c3c415a2ed5c2bb65d
/usr/share/package-licenses/thin-provisioning-tools/4d9d82e016d0ca83bb1f9fb73affcb6d4826a13f
/usr/share/package-licenses/thin-provisioning-tools/4dbe8833d0189c691b308c3dd40fab84ef2e9630
/usr/share/package-licenses/thin-provisioning-tools/4e652e854ac8bcfd9bb61be90d315464c51c4a7a
/usr/share/package-licenses/thin-provisioning-tools/53e358de8d76c2bf7b8a7f899199592f2eb3fe77
/usr/share/package-licenses/thin-provisioning-tools/5798832c31663cedc1618d18544d445da0295229
/usr/share/package-licenses/thin-provisioning-tools/583a5eebcf6119730bd96922e8a0faecf7faf720
/usr/share/package-licenses/thin-provisioning-tools/598f87f072f66e2269dd6919292b2934dbb20492
/usr/share/package-licenses/thin-provisioning-tools/59b5efd50c4508e7fa74828e7469187bbe5bd864
/usr/share/package-licenses/thin-provisioning-tools/5ed53061419caf64f84d064f3641392a2a10fa7f
/usr/share/package-licenses/thin-provisioning-tools/5feaf15b3fa7d2d226d811e5fcd49098a1ea520c
/usr/share/package-licenses/thin-provisioning-tools/60c3522081bf15d7ac1d4c5a63de425ef253e87a
/usr/share/package-licenses/thin-provisioning-tools/669a1e53b9dd9df3474300d3d959bb85bad75945
/usr/share/package-licenses/thin-provisioning-tools/689ec0681815ecc32bee639c68e7740add7bd301
/usr/share/package-licenses/thin-provisioning-tools/68d12a03b339648117165b9c021b93f26974d6f6
/usr/share/package-licenses/thin-provisioning-tools/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a
/usr/share/package-licenses/thin-provisioning-tools/70693ba8757c4a17af68e39ab32e4e0d4a389416
/usr/share/package-licenses/thin-provisioning-tools/7410d07c3621242ce086802924f4c333ff5326bb
/usr/share/package-licenses/thin-provisioning-tools/78b5f27c62ea1f4f238b54f988ea5ddaf65b2a52
/usr/share/package-licenses/thin-provisioning-tools/7963d112b803d110d3e75e932c052284fd208629
/usr/share/package-licenses/thin-provisioning-tools/7a842f34e127456338641b14c7a00ec246d89fb6
/usr/share/package-licenses/thin-provisioning-tools/7df059597099bb7dcf25d2a9aedfaf4465f72d8d
/usr/share/package-licenses/thin-provisioning-tools/8205a96107bd2d30b9a078adcc9eea1bf5eccaf7
/usr/share/package-licenses/thin-provisioning-tools/84bd3ae90fc5fc9eba1babed8039e5085de0d82c
/usr/share/package-licenses/thin-provisioning-tools/8624bcdae55baeef00cd11d5dfcfa60f68710a02
/usr/share/package-licenses/thin-provisioning-tools/86839b96a62723c6b7892a01b25908ff0c108447
/usr/share/package-licenses/thin-provisioning-tools/8838cf14748354bdd25b37507bbb8940248ea5c0
/usr/share/package-licenses/thin-provisioning-tools/8f178d4cc55689ebdd562cabb1282e33bf8f32fe
/usr/share/package-licenses/thin-provisioning-tools/8fe88f09d35c6054e0a780a793833c16fb888168
/usr/share/package-licenses/thin-provisioning-tools/92170cdc034b2ff819323ff670d3b7266c8bffcd
/usr/share/package-licenses/thin-provisioning-tools/9a2b6b4ad55ec42cf19fc686c74668d3a6303ae7
/usr/share/package-licenses/thin-provisioning-tools/9a675655c0a9f0bb9c8109678651fe27bceaca04
/usr/share/package-licenses/thin-provisioning-tools/9f3c36d2b7d381d9cf382a00166f3fbd06783636
/usr/share/package-licenses/thin-provisioning-tools/a00165152c82ea55b9fc254890dc8860c25e3bb6
/usr/share/package-licenses/thin-provisioning-tools/a3b3a65335e78bde163f84d599fa899776552994
/usr/share/package-licenses/thin-provisioning-tools/a6a5418b4d67d9f3a33cbf184b25ac7f9fa87d33
/usr/share/package-licenses/thin-provisioning-tools/a8f3e29d5eab4420318de979754f5637d4bf2c3f
/usr/share/package-licenses/thin-provisioning-tools/aca374a3362a76702c50bd4e7d590a57f8834fc7
/usr/share/package-licenses/thin-provisioning-tools/b716916e6b0b96af5ecadf1eaee25f966f5d6cb2
/usr/share/package-licenses/thin-provisioning-tools/c8eef3d34d69b1d62fd378fa02150a0bce62fd26
/usr/share/package-licenses/thin-provisioning-tools/cd3fe820606ed34ac2591caf068c7cabd3ab3509
/usr/share/package-licenses/thin-provisioning-tools/ce3a2603094e799f42ce99c40941544dfcc5c4a5
/usr/share/package-licenses/thin-provisioning-tools/d223c347f316d191419e643e479caa33bbeae672
/usr/share/package-licenses/thin-provisioning-tools/d74ad13f1402c35008f22bc588a6b8199ed164d3
/usr/share/package-licenses/thin-provisioning-tools/dc5a1036298990ac083baa9bf95f6a1b8ee98c0f
/usr/share/package-licenses/thin-provisioning-tools/dd445710e6e4caccc4f8a587a130eaeebe83f6f6
/usr/share/package-licenses/thin-provisioning-tools/e1c86f32641f01a5b85d6e9b20138e8470b883fc
/usr/share/package-licenses/thin-provisioning-tools/e6d32072ef5f584a805b429ecbd4eec428316dde
/usr/share/package-licenses/thin-provisioning-tools/e9b475b5dccf14bd66d72dd12a04db75eaad1a9e
/usr/share/package-licenses/thin-provisioning-tools/ec9737a4e769cce48d5c95d9c75a4ba5f29a2563
/usr/share/package-licenses/thin-provisioning-tools/f137043e018f2024e0414a9153ea728c203ae8e5
/usr/share/package-licenses/thin-provisioning-tools/f14afa20edce530124d39cd56312c7781c19b267
/usr/share/package-licenses/thin-provisioning-tools/f5feee4154156527645a9b18ef29da23fc859ca9
/usr/share/package-licenses/thin-provisioning-tools/f911b0506e6ba6a56b4edac717b461799f380ef0
/usr/share/package-licenses/thin-provisioning-tools/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man8/cache_check.8
/usr/share/man/man8/cache_dump.8
/usr/share/man/man8/cache_metadata_size.8
/usr/share/man/man8/cache_repair.8
/usr/share/man/man8/cache_restore.8
/usr/share/man/man8/cache_writeback.8
/usr/share/man/man8/era_check.8
/usr/share/man/man8/era_dump.8
/usr/share/man/man8/era_invalidate.8
/usr/share/man/man8/era_restore.8
/usr/share/man/man8/thin_check.8
/usr/share/man/man8/thin_delta.8
/usr/share/man/man8/thin_dump.8
/usr/share/man/man8/thin_ls.8
/usr/share/man/man8/thin_metadata_pack.8
/usr/share/man/man8/thin_metadata_size.8
/usr/share/man/man8/thin_metadata_unpack.8
/usr/share/man/man8/thin_repair.8
/usr/share/man/man8/thin_restore.8
/usr/share/man/man8/thin_rmap.8
/usr/share/man/man8/thin_trim.8
